version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://localhost:5432/postgres'
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy


  k6:
    image: grafana/k6
    container_name: k6
    depends_on:
      springboot:
        condition: service_started
    entrypoint: >
      sh -c "
        while ! nc -z localhost:8080; do
          echo 'Waiting for springboot...';
          sleep 2;
        done;
        k6 run --out cloud /app/GraphqlK6_script.js
      "
    ports:
      - "6565:6565"
    environment:
      K6_CLOUD_TOKEN: ${K6_CLOUD_TOKEN}
      K6_CLOUD_PROJECT_ID: ${K6_CLOUD_PROJECT_ID}
      BASE_URL: "localhost:8080"
    volumes:
      - "${GITHUB_WORKSPACE}:/app"
