name: Testing

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    # Service containers to run with `container-job`

      
    steps:
    - uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
    - name: Set up Docker Compose
      id: ComposeSetup
      run: |
          docker-compose down --remove-orphans
          docker-compose up --build --detach
      env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          
    - name: Check running containers
      if: steps.ComposeSetup.outcome == 'success'
      run: |
            docker ps
            docker network inspect templatelibrary_sql_default
            docker network ls
            docker logs springboot
            
    - name: Run K6 test
      if: steps.ComposeSetup.outcome == 'success'
      run: docker-compose exec k6 k6 run --out cloud /app/GraphqlK6_script.js
