name: Testing

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    # Service containers to run with `container-job`

      
    steps:
    - uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
    - name: Set up Docker Compose
      id: ComposeSetup
      run: |
          docker-compose down --remove-orphans
          docker-compose up --build --detach
          sleep 30 

    - name: Check running containers
      if: steps.ComposeSetup.outcome == 'success'
      run: |
            docker ps
            docker logs springboot
      
    - name: Print environment variables
      run: env

    - name: Run local k6 test
      uses: grafana/run-k6-action@v1
      env:
        K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        BASE_URL: "localhost:8080"
      with:
        path: GraphqlK6_script.js
