name: Testing

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    # Service containers to run with `container-job`

      
    steps:
    - uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
    - name: Set up Docker Compose
      id: ComposeSetup
      run: |
          docker-compose down --remove-orphans
          docker-compose up --build --detach

    - name: Check running containers
      if: steps.ComposeSetup.outcome == 'success'
      run: |
            docker ps
            docker network ls
            docker logs springboot
      
    - name: Print environment variables
      run: env
    - name: Run local k6 test and push results to K6 Cloud
      run: |
        docker run --rm -i \
          -itd --network=templatelibrary_sql_default    \
          -v $(pwd):/app \
          -w /app \
          -e K6_CLOUD_TOKEN=${{ secrets.K6_CLOUD_TOKEN }} \
          -e K6_CLOUD_PROJECT_ID=${{ secrets.K6_CLOUD_PROJECT_ID }} \
          -e BASE_URL="http://springboot:8080" \
          grafana/k6 run --out cloud GraphqlK6_script.js
