name: Testing

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    # Step 3: Start PostgreSQL database
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Install PostgreSQL client
      run: sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: Wait for PostgreSQL to be ready
      run: |
          for i in {1..10}; do
            psql -h localhost -U postgres -d postgres -c '\q' && break || sleep 5
          done

    - name: Run psql command
      env:
        PGPASSWORD: testpassword
      run: |
          psql -h localhost -U postgres -d postgres -c "SELECT version();"
      
    # Step 4: Start application container
    - name: Setup config
      run: |
          mkdir config
          echo 'spring.datasource.url=jdbc:postgresql://localhost:5432/postgres' > config/application.properties

    - name: Run Springboot Application
      id: startApplication
      run: mvn spring-boot:run
      env:
        SPRING_DATASOURCE_URL: 'jdbc:postgresql://localhost:5432/postgres' 
        temp: ${{job.services.postgres.id}}
      
    - name: Print environment variables
      run: env
      
    - name: Setup K6
      if: steps.startApplication.outcome == 'success'
      uses: grafana/setup-k6-action@v1
      

    - name: Run local k6 test
      uses: grafana/run-k6-action@v1
      env:
        K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
        BASE_URL: "localhost:8080"
      with:
        path: GraphqlK6_script.js
